/**
 * Regenerates `src/data/gallery-sizes.ts` from the photos in
 * `src/assets/<section>/`.
 *
 * The gallery discovers its photos with `import.meta.glob`, so dropping files
 * into those folders is enough to get them on the page. What a glob cannot
 * tell you is how big each photo is, and the mosaic needs that to give the
 * portraits the tall slots and to reserve the right box before an image loads.
 * Run `npm run gallery:sizes` after adding or removing photos.
 *
 * Sizes are read straight out of the file headers — no image library, since
 * both formats put the dimensions in the first few hundred bytes.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const assetsDir = join(root, 'src', 'assets')
const outFile = join(root, 'src', 'data', 'gallery-sizes.ts')

/** Section id → folder name. The ids match `gallerySections` in gallery.ts. */
const SECTIONS = ['tournaments', 'hall', 'kids']

const PHOTO_PATTERN = /\.(jpe?g|png|webp)$/i

/** Walks the JPEG marker segments to the frame header, which carries the size. */
function jpegSize(buffer) {
  let offset = 2
  while (offset < buffer.length - 9) {
    if (buffer[offset] !== 0xff) {
      offset += 1
      continue
    }
    const marker = buffer[offset + 1]
    const isFrameHeader =
      marker >= 0xc0 &&
      marker <= 0xcf &&
      marker !== 0xc4 && // Huffman table
      marker !== 0xc8 && // JPEG extension
      marker !== 0xcc // arithmetic coding conditioning
    if (isFrameHeader) {
      return [buffer.readUInt16BE(offset + 7), buffer.readUInt16BE(offset + 5)]
    }
    offset += 2 + buffer.readUInt16BE(offset + 2)
  }
  return null
}

/** PNG puts width and height at a fixed offset in the IHDR chunk. */
function pngSize(buffer) {
  return [buffer.readUInt32BE(16), buffer.readUInt32BE(20)]
}

const entries = []
let count = 0

for (const section of SECTIONS) {
  const files = readdirSync(join(assetsDir, section))
    .filter((file) => PHOTO_PATTERN.test(file))
    .sort()

  entries.push(`  // ${section} — ${files.length} photos`)
  for (const file of files) {
    const buffer = readFileSync(join(assetsDir, section, file))
    const size = /\.png$/i.test(file) ? pngSize(buffer) : jpegSize(buffer)
    if (!size) throw new Error(`could not read dimensions: ${section}/${file}`)
    entries.push(`  '${section}/${file}': [${size[0]}, ${size[1]}],`)
    count += 1
  }
}

const output = [
  '/**',
  ' * Intrinsic pixel size of every gallery photo, keyed by `<section>/<file>`.',
  ' *',
  ' * Generated by `npm run gallery:sizes` — do not edit by hand. A photo that',
  ' * is missing from this map still appears in the gallery, it just falls back',
  ' * to a default landscape box until the script is re-run.',
  ' */',
  'export const photoSizes: Record<string, [width: number, height: number]> = {',
  ...entries,
  '}',
  '',
].join('\n')

writeFileSync(outFile, output)
console.log(`gallery-sizes.ts: ${count} photos across ${SECTIONS.length} sections`)
